name: Nightly release

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    env:
      TAG_NAME: nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          commit: refs/heads/development
          name: Nightly Build
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            /home/runner/work/Microbot/Microbot/runelite-client/target/microbot-*.jar
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Jar
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: runelite-client/target
          container_name: microbot
          connection_string: ${{ secrets.blobConnectionString }}
          extra_args: '--pattern *.jar --destination-path ${{ env.TAG_NAME }}'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'